/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import VTabbed.QuanLyMuaBan;
import VTabbed.QuanLyKhachHangTab;
import VTabbed.QuanLyMatHangTab;
import VTabbed.QuanLyNhaCungCapTab;
import VTabbed.QuanLyNhanVienTab;
import VTabbed.ThongKeTab;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author quang
 */
public class Admin extends JFrame {
    
    private QuanLyKhachHangTab quanLyKhachHangTab;
    private QuanLyMatHangTab quanLyMatHangTab;
    private QuanLyMuaBan quanLyMuaBanTab;
    private QuanLyNhanVienTab quanLyNhanVienTab;
    private ThongKeTab thongKeTabbed;
    private QuanLyNhaCungCapTab quanLyNhaCungCapTab;
    
    private void prepareUI() throws Exception{
        if(DangNhap.taiKhoan.getLoaiTaiKhoan()==1){
            TabKhachHang.add("Quản Lý Khách Hàng",quanLyKhachHangTab = new QuanLyKhachHangTab());
            TabKhachHang.add("Quản Lý Nhà Cung Cấp",quanLyNhaCungCapTab = new QuanLyNhaCungCapTab());
            TabKhachHang.add("Quản Lý Mặt Hàng",quanLyMatHangTab = new QuanLyMatHangTab());
            TabKhachHang.add("Quản Lý Mua Bán",quanLyMuaBanTab = new QuanLyMuaBan());
            TabKhachHang.add("Quản Lý Nhân Viên",quanLyNhanVienTab = new QuanLyNhanVienTab());
            TabKhachHang.addTab("Thống kê", thongKeTabbed = new ThongKeTab());
        }
        else{
            TabKhachHang.add("Quản Lý Khách Hàng",quanLyKhachHangTab = new QuanLyKhachHangTab());
            TabKhachHang.add("Quản Lý Mặt Hàng",quanLyMatHangTab = new QuanLyMatHangTab());
            TabKhachHang.add("Quản Lý Mua Bán",quanLyMuaBanTab = new QuanLyMuaBan());
            TabKhachHang.addTab("Thống kê", thongKeTabbed = new ThongKeTab());
        }
        
        
        TabKhachHang.addChangeListener(menuTabbed_Change());
    }
    
    /**
     * Sự kiện khi chọn 1 tab
     *
     * @return
     */
    private ChangeListener menuTabbed_Change() {
        return new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                try {
                    quanLyKhachHangTab.refresh(true);
                    quanLyNhaCungCapTab.refresh(true);
                    quanLyMatHangTab.refresh(true);
                    quanLyMuaBanTab.refresh(true);
                    quanLyNhanVienTab.refresh(true);
                    thongKeTabbed.refresh();

                }catch(Exception e1){
                    return;
                }

                TabKhachHang.revalidate();
                TabKhachHang.repaint();
            }
        };
    }
    
    
    
    
    /**
     * Creates new form Main
     */
    public Admin() throws Exception {
        initComponents();
        
        
        
         prepareUI();
         setLocationRelativeTo(null);
        setSize(1400, 750);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabKhachHang = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TabKhachHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 1186, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabKhachHang;
    // End of variables declaration//GEN-END:variables
}
