USE master
GO



--========== TẠO DATABASE  ==========--
CREATE DATABASE QUANLYBANHANGVERSION1
GO

USE QUANLYBANHANGVERSION1
GO



--========== TẠO BẢNG ==========--
CREATE TABLE THONGTINCANHAN
(
    CMND      VARCHAR(20)  NOT NULL,
    HOTEN     NVARCHAR(50) NOT NULL,
    DIENTHOAI VARCHAR(20),
    DIACHI    NVARCHAR(100),
    GIOITINH  INT          NOT NULL,
    NGAYSINH  DATE,
    CONSTRAINT THONGTINCANHAN_CK_GIOITINH CHECK (GIOITINH IN (0, 1)),
    CONSTRAINT THONGTINCANHAN_PK PRIMARY KEY (CMND)
)
GO

CREATE TABLE KHACHHANG
(
    MAKH       VARCHAR(10) NOT NULL,
    CMND       VARCHAR(20) NOT NULL,
    NGAYTHAMGIA DATE,
    CONSTRAINT KHACHHANG_PK PRIMARY KEY (MAKH),
    CONSTRAINT KHACHHANG_FK_THONGTINCANHAN FOREIGN KEY (CMND) REFERENCES THONGTINCANHAN (CMND) ON DELETE CASCADE
)
GO

CREATE TABLE NHANVIEN
(
    MANV VARCHAR(10) NOT NULL,
    CMND VARCHAR(20) NOT NULL,
    MOTA NVARCHAR(100),
    CONSTRAINT NHANVIEN_PK PRIMARY KEY (MANV),
    CONSTRAINT NHANVIEN_FK_THONGTINCANHAN FOREIGN KEY (CMND) REFERENCES THONGTINCANHAN (CMND) ON DELETE CASCADE
)
GO

CREATE TABLE TAIKHOAN
(
    TENTAIKHOAN VARCHAR(30)   NOT NULL,
    MATKHAU     NVARCHAR(128) NOT NULL,
    LOAITK      SMALLINT      NOT NULL,
    MANV        VARCHAR(10)   NOT NULL,
    CONSTRAINT TAIKHOAN_PK PRIMARY KEY (TENTAIKHOAN),
    CONSTRAINT TAIKHOAN_FK_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV) ON DELETE CASCADE
)
GO



CREATE TABLE NHACUNGCAP(
    MANCC NVARCHAR(30) NOT NULL,
    TENNCC NVARCHAR(30) NOT NULL,
    DIACHI NVARCHAR(30) NOT NULL,
    DIENTHOAI NVARCHAR(30) NOT NULL,
    CONSTRAINT NHACUNGCAP_PK PRIMARY KEY (MANCC)

)
GO


CREATE TABLE MATHANG
(
    MAMH        NVARCHAR(10) NOT NULL,
    TENMH       NVARCHAR(50) NOT NULL,
    MANCC NVARCHAR(30) NOT NULL,
    GHICHU      NVARCHAR(100),
    DONGIA      MONEY        NOT NULL,
    TINHTRANG   INT,
    THELOAI     NVARCHAR(30) NOT NULL,
    SOLUONGTON  INT          NOT NULL,
    CONSTRAINT MATHANG_PK PRIMARY KEY (MAMH),
    CONSTRAINT MATHANG_CK_TINHTRANG CHECK (TINHTRANG IN (0, 1)),
    CONSTRAINT MATHANG_FK_NHACUNGCAP FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP (MANCC)
)
GO






CREATE TABLE HOADON
(
    MAHD    VARCHAR(10) NOT NULL,
    NGAYLAP DATE,
    MAKH    VARCHAR(10) NOT NULL,
    TINHTRANG   INT NOT NULL,
    CONSTRAINT HOADON_PK PRIMARY KEY (MAHD),
    CONSTRAINT HOADON_FK_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH)
)
GO




CREATE TABLE CHITIETHOADON
(
    ID             INT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
    MAHD           VARCHAR(10)  NOT NULL,
    MAMH           NVARCHAR(10) NOT NULL,
    TENMH          NVARCHAR(50)      NOT NULL,
    SOLUONG        INT          NOT NULL,
    
    CONSTRAINT CHITIETHOADON_FK_MATHANG FOREIGN KEY (MAMH) REFERENCES MATHANG (MAMH),
    CONSTRAINT CHITIETHOADON_FK_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON (MAHD) ON DELETE CASCADE
)
GO

--true: đã trả, false: đang thuê

-- insert into CHITIETHOADON VALUES('00022','0001',45,3,1)


ALTER TABLE KHACHHANG
    ADD CONSTRAINT KHACHHANG_DF_NGAYTHAMGIA DEFAULT GETDATE() FOR NGAYTHAMGIA
GO

ALTER TABLE MATHANG
    ADD CONSTRAINT MATHANG_DF_TINHTRANG DEFAULT 1 FOR TINHTRANG
GO

ALTER TABLE HOADON
    ADD CONSTRAINT HOADON_DF_NGAYLAP DEFAULT GETDATE() FOR NGAYLAP
GO


--========== VIEW --==========
CREATE VIEW VIEW_THONGTINKHACHHANG AS
SELECT T.CMND,
       K.MAKH,
       HOTEN,
       DIENTHOAI,
       DIACHI,
       GIOITINH,
       NGAYSINH,
       NGAYTHAMGIA
FROM THONGTINCANHAN T
         INNER JOIN KHACHHANG K
                    ON T.CMND = K.CMND
GO

CREATE VIEW VIEW_THONGTINMATHANG AS
SELECT  T.MAMH,
        T.TENMH,
        K.TENNCC,
        T.THELOAI,
        T.TINHTRANG,
        T.MANCC,
        T.GHICHU,
        T.DONGIA,
        T.SOLUONGTON
FROM MATHANG T
         INNER JOIN NHACUNGCAP K
                    ON T.MANCC = K.MANCC
GO



-- This view will query all the info about nhanvien (INCLUDE ADMIN AND NHANVIEN)
CREATE VIEW VIEW_THONGTINNHANVIEN AS
SELECT T.CMND,
       N.MANV,
       HOTEN,
       DIENTHOAI,
       DIACHI,
       GIOITINH,
       NGAYSINH,
       MOTA
FROM THONGTINCANHAN T
         INNER JOIN NHANVIEN N
                    ON T.CMND = N.CMND
GO


-- This view will query all info about nhanvien where LOAITAIKHOAN=0 (INCLUDE NHANVIEN)
-- CREATE VIEW VIEW_THONGTINNHANVIEN AS
-- SELECT T.CMND,
--        N.MANV,
--        HOTEN,
--        DIENTHOAI,
--        DIACHI,
--        GIOITINH,
--        NGAYSINH,
--        MOTA
-- FROM THONGTINCANHAN T
--          INNER JOIN NHANVIEN N ON T.CMND = N.CMND
                    
-- WHERE N.MANV
--        =(SELECT * FROM MANV1)
-- GO



-- CREATE VIEW MANV1 AS
-- SELECT MANV FROM TAIKHOAN
-- WHERE LOAITK=0
-- GO




-- SELECT * FROM MANV1

-- SELECT * FROM TAIKHOAN


-- SELECT * FROM VIEW_THONGTINNHANVIEN1



-- ========== TRIGGER ==========--
CREATE TRIGGER TRG_THEMHOADON
    ON CHITIETHOADON
    AFTER INSERT AS
BEGIN
    UPDATE MATHANG
    SET SOLUONGTON = SOLUONGTON - (
        SELECT SOLUONG
        FROM inserted
        WHERE MAMH = B.MAMH
    )
    FROM MATHANG B
             JOIN inserted I
                  ON B.MAMH = I.MAMH
END
GO

CREATE TRIGGER TRG_CAPNHATHOADON
    ON CHITIETHOADON
    AFTER UPDATE AS
BEGIN
    UPDATE MATHANG
    SET SOLUONGTON = SOLUONGTON -
                     (SELECT SOLUONG FROM inserted  WHERE MAMH = B.MAMH) +
                     (SELECT SOLUONG FROM deleted  WHERE MAMH = B.MAMH)
    FROM MATHANG B
             JOIN deleted D
                  ON B.MAMH = D.MAMH
end
GO

-- CREATE TRIGGER TRG_XOAHOADON
--     ON CHITIETHOADON
--     FOR DELETE AS
-- BEGIN
--     UPDATE MATHANG
--     SET SOLUONGTON = SOLUONGTON - (
--         SELECT SUM(SOLUONG)
--         FROM deleted
--         WHERE MAMH = B.MAMH)
--     FROM MATHANG B
--              JOIN deleted D
--                   ON B.MAMH = D.MAMH
-- END
-- GO



CREATE PROCEDURE THANHTOAN_HOADON(@maHoaDon VARCHAR(10)) AS
BEGIN
    UPDATE HOADON
    SET TINHTRANG = 1
    WHERE MAHD = @maHoaDon
END
GO

CREATE PROCEDURE TRAHANG_HOADON(@maHoaDon VARCHAR(10)) AS
BEGIN
    UPDATE HOADON
    SET TINHTRANG = -1
    WHERE MAHD = @maHoaDon

    UPDATE MATHANG
    SET SOLUONGTON = SOLUONGTON + (SELECT SUM(SOLUONG) FROM CHITIETHOADON WHERE MAHD = @maHoaDon)
    WHERE MAMH = (SELECT MAMH FROM CHITIETHOADON WHERE MAHD = @maHoaDon)
END
GO



--========== THÊM DỮ LIỆU ==========--
USE QUANLYBANHANGVERSION1
GO

INSERT INTO THONGTINCANHAN (CMND, HOTEN, DIENTHOAI, DIACHI, GIOITINH, NGAYSINH)
VALUES ('030200006929', 'Nguyen Van Chinh', '0982505701', 'Minh Khai Ha Noi', 1, '1999-02-24')
GO

INSERT INTO NHANVIEN (MANV, CMND, MOTA)
VALUES ('NV00001', '030200006929', 'ADMIN')
GO

INSERT INTO TAIKHOAN (TENTAIKHOAN, MATKHAU, LOAITK, MANV)
VALUES ('admin', 'admin', 1, 'NV00001')
GO



-- INSERT INTO THONGTINCANHAN (CMND, HOTEN, DIENTHOAI, DIACHI, GIOITINH, NGAYSINH)
-- VALUES ('051600613264', 'Nguyen Xuan Thu', '03356845245', 'Minh Khai Ha Noi', 1, '2000-12-01')
-- GO

-- INSERT INTO NHANVIEN (MANV, CMND, MOTA)
-- VALUES ('NV00002', '051600613264', 'Nhan vien moi')
-- GO

-- INSERT INTO TAIKHOAN (TENTAIKHOAN, MATKHAU, LOAITK, MANV)
-- VALUES ('user1', 'user', 0, 'NV00002')
-- GO







-- INSERT INTO MATHANG (MAMH, TENMH, MANCC, GHICHU, DONGIA, TINHTRANG, THELOAI, SOLUONGTON) VALUES ('12312','Tivi','Hoa Dong','NC00001','test',1200000,'Dien tu',3);
-- GO



-- INSERT INTO CHITIETHOADON (MAHD,MAMH,SOLUONG,TINHTRANG)
-- VALUES ('HDB00008', 'MH00008', 2, 1)
-- GO

